name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: lvlcn-t/meta/.github/workflows/test.yml@main
    with:
      go_version_file: go.mod
      golangci_config: .golangci.yaml
      additional_args: -v
